name: rick_and_morty_app
description: A Flutter app that displays Rick and Morty characters with favorites and offline cache.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_bloc: ^8.1.3
  equatable: ^2.0.5


  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  http: ^1.2.1


  go_router: ^8.0.4


  cached_network_image: ^3.3.1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
